name: Sync S3 Bucket and CloudFront Invalidation

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name

jobs:
  sync-s3-and-invalidate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i -g aws-sdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your bucket's region

      - name: Delete existing files in S3 bucket
        run: |
          aws s3 rm s3://mytest-awsugblr-bucket/ --recursive

      - name: Clone GitHub repository
        run: git clone https://github.com/sankara-sabapathy/acd2024.git

      - name: Sync repository contents with S3 bucket
        run: |
          ls
          cd acd2024
          aws s3 sync . 3://mytest-awsugblr-bucket --delete

      # - name: Create CloudFront invalidation
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id your-distribution-id --paths "/*"
      #   env:
      #     AWS_DEFAULT_REGION: your-cloudfront-region  # Replace with your CloudFront region
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
